// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vlycposuyicgnozzuvsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseWNwb3N1eWljZ25venp1dnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjcyNDksImV4cCI6MjA1ODcwMzI0OX0.8Fol1BWaomNMv-6xx8Eb2A9bONoDNDMHnYIzfU-Edo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);